name: Deploy DEKKO to server

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-over-ssh:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write
      id-token: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master
          submodules: recursive
          ref: v1.5.2

      - name: Install SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add bastion to SSH config
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_BASTION: ${{ secrets.SSH_BASTION }}
        run: |
          cat <<EOF > ~/.ssh/config
          Host ${SSH_HOST}
            IdentityFile ~/.ssh/id_rsa
            ProxyJump deployment@${SSH_BASTION}

          Host ${SSH_BASTION}
            IdentityFile ~/.ssh/id_rsa

          Host *
              StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Stop DEKKO service on remote server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa ${SSH_USER}@${SSH_HOST} -o StrictHostKeyChecking=no 'sudo /bin/systemctl stop DEKKO.service'

      - name: Copy files to remote server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_BASTION: ${{ secrets.SSH_BASTION }}
        run: >
          rsync -avzr --delete
          --exclude 'config.py'
          --exclude 'database.db'
          --exclude '.git*'
          --exclude 'outtmpl*'
          --exclude 'README.md'
          --exclude '.venv*'
          -e 'ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'
          ./master/
          ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/DEKKO

      - name: Start DEKKO service on remote server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa ${SSH_USER}@${SSH_HOST} -o StrictHostKeyChecking=no 'sudo /bin/systemctl start DEKKO.service'
