name: Deploy DEKKO to server

on:
  push:
    branches:
      - master

jobs:
  deploy-over-ssh:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write
      id-token: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master
          submodules: recursive

      - name: Install SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p .ssh
          echo "$PRIVATE_KEY" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

      - name: Add Bastion to SSH Config
        run: |
          cat <<EOF > .ssh/config
          Host ${{ secrets.SSH_HOST }}
              ProxyJump deployment@${{ secrets.SSH_BASTION }}
          EOF

      - name: Stop DEKKO Service on Remote Server
        run: |
          ssh -i .ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no 'sudo /bin/systemctl stop DEKKO.service'

      - name: Copy Files to Remote Server
        run: |
          rsync -avzr --delete --exclude node_modules --exclude '.git*' -e 'ssh -i .ssh/id_rsa -o StrictHostKeyChecking=no' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/DEKKO
